### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by harshinsecurity** [ashigup/corobuster#1]
File "corobuster.py", line 36,
    c=str(sys.argv[2])
IndexError: list index out of range

**Comment by ashigup** [comment]
I think you had not read the syntax of the tool carefully.
You are getting the specified error because you are not passing enough parameters.
At least two parameters i.e. URL of the target and wordlist to be used need to be passed. 
So try it by passing correct parameters in sequence and even then if you get any error, feel free to contact me.
